services:
  web:
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    ports:
      - "8080:80"           # http://localhost:8080
    volumes:
      - .:/var/www/html     # DocumentRoot は /var/www/html/public
    depends_on:
      - db

  db:
    image: mariadb:11
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=myapp
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"         # 競合するならこの行を消してOK
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
